; PlatformIO Project Configuration File for Profiler
;
; This repository is designed to work with both PlatformIO and Arduino 
;
; To use with PlatformIO: 
; cd src; ln -s ../Profiler.ino Profiler.cpp
;
; To use with ArduinoIDE:
; rm -rf .pio/
; rm src/Profiler.cpp

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
; Save the hex file to the project directory
extra_scripts = post:hex_save.py
# Add ./ as an include directory so that src/*.h files will be found
build_flags = -I./
board_build.f_cpu = 150000000L # Set the CPU frequency to 150 MHz
lib_deps = 
  https://github.com/kalnajslab-org/SerialComm.git
  https://github.com/kalnajslab-org/RPUComm.git
  https://github.com/kalnajslab-org/Tsensor1Wire.git
  https://github.com/kalnajslab-org/RS41.git
  mikalhart/TinyGPSPlus@^1.1.0
  https://github.com/tonton81/WDT_T4.git
  LoRa

